### ISSUE TITLE
Render html template

### ISSUE THREAD

**Issue by mvfsillva** [rodrigo-picanco/dynamic-template#1]
Hey, What do you think of also rendering an HTML?

Example:

```js
const renderLink = '<a href="/">Click Here</a>'
const message = 'Hello folks ${clickHere} for view new posts'
const renderMessage = dynamicTemplate(message, { clickHere: renderLink }) 
```

**Comment by rodrigo-picanco** [comment]
Hello @mvfsillva, thank you for your question! :smile: 

In fact, dynamic-template already can render html. 

[I created a sandbox to showcase this](https://codesandbox.io/s/dynamic-string-html-interpolation-ym90q?file=/src/index.js), I'm adding it to the README as well.

**Comment by rodrigo-picanco** [comment]
I'm therefore closing this one. Thank you again!
